# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ApiGrpc/service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'ApiGrpc/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x41piGrpc/service.proto\x12\x17LichessAnalyzerForecast\"a\n\x14PredictRatingRequest\x12\x30\n\x07ratings\x18\x01 \x03(\x0b\x32\x1f.LichessAnalyzerForecast.Rating\x12\x17\n\x0fnum_predictions\x18\x02 \x01(\x05\"&\n\x06Rating\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06rating\x18\x02 \x01(\x01\"M\n\x15PredictRatingResponse\x12\x34\n\x0bpredictions\x18\x01 \x03(\x0b\x32\x1f.LichessAnalyzerForecast.Rating2\x81\x01\n\x0fRatingPredictor\x12n\n\rPredictRating\x12-.LichessAnalyzerForecast.PredictRatingRequest\x1a..LichessAnalyzerForecast.PredictRatingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ApiGrpc.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTRATINGREQUEST']._serialized_start=50
  _globals['_PREDICTRATINGREQUEST']._serialized_end=147
  _globals['_RATING']._serialized_start=149
  _globals['_RATING']._serialized_end=187
  _globals['_PREDICTRATINGRESPONSE']._serialized_start=189
  _globals['_PREDICTRATINGRESPONSE']._serialized_end=266
  _globals['_RATINGPREDICTOR']._serialized_start=269
  _globals['_RATINGPREDICTOR']._serialized_end=398
# @@protoc_insertion_point(module_scope)
