@startuml

skinparam ConditionStyle InsideDiamond

|Пользователь|
start
repeat
    :Определить тип
    шахматиста;
    if (Клубный шахматист?) then (да)
      :Перейти на страницу клуба;
    else (нет)
      :Перейти в каталог поиска шахматистов;
    endif
    
    :Выбрать шахматиста
    для получения активности;
    
    |Lichess.org|
    :Переход на страницу с информацией;
    :Получение данных;
    :Отображение страницы;
    
    |Пользователь|
    :Перенос информации в хранилище;
   
repeat while (Информация о всех\nшахматистах получена)

:Анализ полученных данных;

stop

@enduml
