@startuml

skinparam ConditionStyle foo1

|Клиентское приложение|
start

:Запрос данных
о сущности;

|Кэш|
:Проверка наличия
данных;

if (Данные присутствуют?) is (да) then
  |Клиентское приложение|
  :Получение данных;
  stop
else (нет)
  |Кэш|
  :Вернуть пустой ответ;
  |Клиентское приложение|
  :Запрос данных о сущности;
endif

|API|
:Получение всей
информации о сущности;
split
    :Возвращение
    нужной части данных пользователю;
    
    |Клиентское приложение|
    :Получение
    данных;
    end
split again
    |API|
    :Отправка
    данных
    в кэш;
    
    |Кэш|
    :Сохранение
    сущности;

end

@enduml
