' account mgm

@startuml login

autonumber
autoactivate on

actor "Пользователь" as user
participant "Приложение" as app

user -> app: Нажатие кнопки входа
app --> user: Страница входа

user -> app: Нажатие кнопки входа через Lichess.org
app --> user: Перенаправление на стороннюю страницу входа

alt Разрешение на доступ
    user -> app: Подтверждение авторизации
    app --> user: Перенаправление на страницу профиля
else Отказ предоставления разрешения на доступ
    autonumber 5
    user -> app: Отказ от авторизации
    app --> user: Сообщение о неудавшейся авторизации
end

@enduml

@startuml logout

autonumber
autoactivate on

actor "Пользователь" as user
participant "Приложение" as app

user -> app: Нажатие кнопки перехода в профиль
return Страница профиля

user -> app: Нажатие кнопки выхода из аккаунта
return Форма подтверждения выхода

alt Пользователь подтверждает выход
    user -> app: Нажатие кнопки подтверждения выхода
    app -> app: Деактивация сессии пользователя
    app --> user: Главная страница приложения
else Пользователь отменяет выход
    autonumber 5
    user -> app: Нажатие кнопки отмены выхода
    app --> user: Закрытие формы подтверждения
end

@enduml

@startuml delete-account

autonumber
autoactivate on

actor "Пользователь" as user
participant "Приложение" as app

user -> app: Нажатие кнопки перехода в профиль
return Страница профиля

user -> app: Нажатие кнопки удаления аккаунта
return Форма подтверждения удаления

alt Пользователь подтверждает выход
    user -> app: Нажатие кнопки подтверждения удаления
    app -> app: Деактивация сессии пользователя
    app -> app: Удаление пользователя из базы данных
    app --> user: Главная страница приложения
else Пользователь отменяет выход
    autonumber 5
    user -> app: Нажатие кнопки отмены удаления
    app --> user: Закрытие формы подтверждения
end

@enduml

' analytics lists mgm


@startuml view-lists

autonumber
autoactivate on

actor "Пользователь" as user
participant "Приложение" as app

opt Авторизоваться
   user --> app: Авторизация 
end

user -> app: Нажатие кнопки перехода на страницу списков

opt Пользователь авторизован
    app -> app: Получение списков
end

alt Списки присутствуют
    app --> user: Возврат страницы со списками
    user -> app: Нажатие на список
    
    app -> app: Получение информации о шахматистах списка,\nотрисовка дашборда
    
    app --> user: Предоставление страницы дашборда списка
    
    opt Нужно экспортировать данные о шахматистах
        user -> app: Нажатие кнопки экспорта данных о шахматистах
        
        app -> user: Форма с выбором формата файла или отменой экспорта
        
        alt Пользователь выбирает формат файла
            user -> app: Нажатие кнопки с типом файла
            app -> app: Сборка данных в файл
            app --> user: Отправка файла, закрытие формы
        else Пользователь отменяет экспорт
            autonumber 10
            user -> app: Нажатие кнопки отмены
            app --> user: Закрытие формы
        end
    end
    
    opt Нужно экспортировать отчет (дашборд)
        user -> app: Нажатие кнопки экспорта отчета
        app -> user: Форма с выбором формата файла или отменой экспорта
        alt Пользователь выбирает формат файла
            user -> app: Нажатие кнопки с типом файла
            app -> app: Конвертация представления дашборда
            app --> user: Отправка файла, закрытие формы
        else Пользователь отменяет экспорт
            autonumber 14
            user -> app: Нажатие кнопки отмены
            app --> user: Закрытие формы
        end
    end
else Списков нет
    autonumber 4
    app --> user: Сообщение о том, что списков нет
end

@enduml

@startuml create-list

autonumber
autoactivate on

actor "Пользователь" as user
participant "Приложение" as app

user -> app: Переход на страницу списков
app --> user: Предоставление страницы со списками

user -> app: Нажатие кнопки создания нового списка
app --> user: Возврат страницы с редактированием названия списка,\nвкладками и страницами с поиском\nпо шахматистам и клубам соответственно,\nпанель с выбранными шахматистами

user --> app: Ввод названия списка
loop Нужно добавить шахматистов в список
    alt Поиск по шахматистам
        user -> app: Нажатие на кнопку поиска по шахматистам
        app -> app: Включение режима поиска по шахматистам
        app --> user: Отображение выбранного режима поиска по шахматистам 
    else Поиск по клубам
        autonumber 8
        user -> app: Нажатие на кнопку поиска по клубам
        app -> app: Включение режима поиска по клубам
        app --> user: Отображение выбранного режима поиска по клубам
    end 
    alt Поиск по ID
        user -> app: Нажатие на кнопку поиска по ID
        app -> app: Включение режима поиска по ID
        app --> user: Отображение выбранного режима поиска по ID
        
        user --> app: Ввод ID в поле поиска
        user -> app: Нажатие кнопки поиска
        app -> app: Поиск сущности по ID
        alt Найдена сущность
            app --> user: Структура сущности в окне результата поиска
        else Сущность с ID не найдена
            autonumber 17
            app --> user: Сообщение об отсутствии сущности с таким ID
        end
    else Поиск по имени
        autonumber 11
        user -> app: Нажатие на кнопку поиска по имени
        app -> app: Включение режима поиска по имени
        app --> user: Отображение выбранного режима поиска по имени
        
        user --> app: Ввод имени в поле поиска
        app --> user: Результаты совпадений имен в выпадающем списке
        user -> app: Нажатие на подходящее имя из списка
        app -> app: Получение выбранной сущности
        app --> user: Структура сущности в окне результата поиска
    end
    
    user -> app: Нажатие кнопки добавления сущности (шахматист или клуб) в список
    app -> app: Сохранение шахматиста (шахматистов) в список добавляемых
    app --> user: Обновление представления списка добавляемых шахматистов
end

user -> app: Нажатие кнопки подтверждения создания списка
app -> app: Создание списка на основе выбранных шахматистов

alt Создание успешно
    app --> user: Перенаправление на страницу с созданным списком
else Произошла ошибка 
    autonumber 24
    app --> user: Возврат сообщения об ошибке 
end

@enduml


@startuml edit-list

autonumber
autoactivate on

actor "Пользователь" as user
participant "Приложение" as app

user -> app: Переход на страницу списков
app --> user: Предоставление страницы со списками

opt Нужно отредактировать название
    user -> app: Нажатие кнопки редактирования рядом со списком
    app -> user: Форма редактирования названия
    user --> app: Ввод нового названия
    user -> app: Подтверждение
    app -> app:  Обновление названия
    app --> user: Страница с обновленным списком
end

opt Нужно добавить шахматистов в список
    user -> app: Нажатие кнопки добавления шахматистов
    app --> user: Страница с добавлением шахматистов
    user --> app: Выбор шахматистов
    user -> app: Подтверждение добавления
    app -> app: Добавление шахматистов
    app --> user: Страница с обновленным списком
end

opt Нужно удалить шахматистов из списка
    user -> app: Нажатие кнопки удаления шахматистов
    app --> user: Страница с удалением шахматистов
    user --> app: Выбор шахматистов
    user -> app: Подтверждение удаления
    app -> app: Удаление шахматистов
    app --> user: Страница с обновленным списком
end

opt Нужно удалить список
    user -> app: Нажатие кнопки удаления списка
    app -> user: Форма подтверждения
    user -> app: Подтверждение
    activate user
    app -> app: Удаление списка
    app --> user: Страница со списками
end

@enduml