@startuml

actor Пользователь as user

usecase (1. Поиск шахматиста) as searchPlayer  
usecase (2. Поиск клуба) as searchClub
usecase (3. Выбор шахматистов\nдля добавления) as choosePlayers 
usecase (4. Создать пустой список) as createEmpty
    usecase (5. Создать список\nна основе\nнайденных шахматистов) as createByPlayers 
    usecase (6. Создать список\nна основе\nнайденных клубов) as createByClubs 
    usecase (7. Просмотреть\nсписок из каталога) as readList 
    usecase (8. Редактировать\nназвание списка) as editList
    usecase (9. Удалить списки) as deleteList
    usecase (10. Добавить\nшахматистов в список) as addPlayer 
    usecase (11. Удалить\nшахматистов из списка) as deletePlayer
    usecase (12. Экспорт\nсозданных списков) as exportList
    usecase (13. Составить\nотчет) as createDashboard 
    usecase (14. Экспорт отчета) as exportDashboard

    user - createDashboard
        createDashboard <.u. exportDashboard : <<extend>>
        createDashboard .r.> readList : <<include>>
            readList <.u. createEmpty : <<extend>>
            readList <.. createByClubs : <<extend>>
                createByClubs ..> searchClub : <<include>>
            readList <.. createByPlayers : <<extend>>
                createByPlayers ..> choosePlayers : <<include>>
                    choosePlayers .l.> searchPlayer : <<include>>
                    choosePlayers <. searchClub : <<extend>>
            readList <.u. editList : <<extend>>
            readList <.. deleteList : <<extend>>
            readList <.u. exportList : <<extend>>
            readList <. deletePlayer : <<extend>>
            readList <.. addPlayer : <<extend>>
                addPlayer ..> choosePlayers : <<include>>
}

@enduml